---
- name: Allow artifactory_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ artifactory_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: Set environment vars for basic access
  command: "{{ item }}"
  with_items:
    - 'export ARTI_USERNAME={{ artifactory_user }}'
    - 'export ARTI_PASSWORD={{ artifactory_password }}'
  when: artifactory_auth == 'basic'

- name: Set environment vars for token access
  command: export ARTI_ACCESS_TOKEN={{ artifactory_token }}
  when: artifactory_auth == 'token'