---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ artifactory_exporter_dependencies }}"

- name: Create the artifactory_exporter group
  group:
    name: "{{ artifactory_exporter_system_group }}"
    state: present
    system: true

- name: Create the artifactory_exporter user
  user:
    name: "{{ artifactory_exporter_system_user }}"
    groups: "{{ artifactory_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- name: Download artifactory_exporter binary to local folder
  become: false
  get_url:
    url: "https://github.com/peimanja/artifactory_exporter/releases/download/v{{ artifactory_exporter_version }}/artifactory_exporter-{{ artifactory_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp/artifactory_exporter-{{ artifactory_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
#    checksum: "sha256:{{ artifactory_exporter_checksum }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Unpack artifactory_exporter binary
  become: false
  unarchive:
    src: "/tmp/artifactory_exporter-{{ artifactory_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/artifactory_exporter-{{ artifactory_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/artifactory_exporter"
  delegate_to: localhost
  check_mode: false

- name: Propagate artifactory_exporter binaries
  copy:
    src: "/tmp/artifactory_exporter-{{ artifactory_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/artifactory_exporter"
    dest: "/usr/local/bin/artifactory_exporter"
    mode: 0750
    owner: "{{ artifactory_exporter_system_user }}"
    group: "{{ artifactory_exporter_system_group }}"
  notify: restart artifactory_exporter
  when: not ansible_check_mode

- name: Copy the artifactory_exporter systemd service file
  template:
    src: artifactory_exporter.service.j2
    dest: /etc/systemd/system/artifactory_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart artifactory_exporter
